[package]
name = "gesture_extractor"
version = "0.1.0"
authors = ["Tom Dymel <tom.dymel@tuhh.de>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
strum = "0.19"
strum_macros = "0.19"
plotters = "0.3"
rand = "0.7"