[package]
name = "gesture_extractor"
version = "0.1.0"
authors = ["Tom Dymel <tom.dymel@tuhh.de>"]
edition = "2018"

[dependencies]
lib_gesture = { path = "../lib_gesture", version = "*" }
lib_feature = { path = "../lib_feature", version = "*" }
strum = "0.19"