use std::collections::HashMap;

use crate::entities::DataSetEntry;
use crate::value_objects::{AdditionalSpecification, BrightnessLevel, CameraDistance, CoveringObject, DataSetName, ParsingMethod};

lazy_static! {
    /// Automatically parses the dataDymel data set, once this constant is imported.
    /// Note: This set only supports the ByAnnotation ParsingMethod.
    pub static ref DYMEL_DATA: HashMap<ParsingMethod, Vec<DataSetEntry>> = {
        let path_test: String = format!("{}/data/dataDymel", std::env::var("DATA_PATH").unwrap());
        let mut result = HashMap::new();
        result.insert(ParsingMethod::ByAnnotation, vec![
            // LowBrightness
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_lowBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_lowBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_lowBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_lowBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Low,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            // MediumBrightness
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_mediumBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_mediumBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_mediumBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_mediumBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::Medium,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            // HighBrightness
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "LRRL_highBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::Fast), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "TBBT_highBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::Slow), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_Corner_highBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureCorner), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_5cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_5cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM5, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_10cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_10cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM10, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_20cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_20cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM20, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_25cm_fast.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
            DataSetEntry::new(format!("{}/{}", path_test, "NULL_SameInAndOut_highBrightness_25cm_slow.csv"), DataSetName::DymelTest,
                CoveringObject::Hand, CameraDistance::CM25, BrightnessLevel::High,
                Some(AdditionalSpecification::NullGestureSameInAndOut), ParsingMethod::ByAnnotation),
        ]);
        result
    };
}