[package]
name = "lib_feature"
version = "0.1.0"
authors = ["Tom Dymel <td@wps.de>"]
edition = "2018"

[dependencies]
lib_gesture = { path = "../lib_gesture", version = "*" }
strum = "0.19"
strum_macros = "0.19"