/*!
Once these gesture (candidates) are parsed, features can be extracted from them. This library defines how a certain parameter (features) can be
extracted from a gesture. Once a feature is defined in terms of the `Feature` trait, it has to be added to the `FeatureType` in order to be
automatically generated by the `feature_extractor`.
*/

extern crate lib_gesture;
extern crate strum;
#[macro_use]
extern crate strum_macros;

pub use self::features::*;

mod features;